"""create tables Ansible

Revision ID: bbcc98ff7453
Revises: 
Create Date: 2023-04-03 16:33:14.054088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcc98ff7453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ansibles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory', sa.String(length=255), nullable=True),
    sa.Column('playbook', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('extra_vars', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ansibles_id'), 'ansibles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ansibles_id'), table_name='ansibles')
    op.drop_table('ansibles')
    # ### end Alembic commands ###
